#!/usr/bin/env bash

EXE="./target/debug/ece461_team19_cli"
RELEASE_EXE="./target/release/ece461_team19_cli"

if [[ "$1" == "build" ]]; then
    # build program
    cargo build --release
elif [[ "$1" == "install" ]]; then
    # TODO list of dependencies to install
    echo "install what"
elif [[ "$1" == "test" ]]; then
    # TODO generate test reports
    "$EXE" report some_report_file.profdata
else
    # parse url file
    "$RELEASE_EXE" url $1
fi
